// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWApQqZcIGQWVm7dOFNcWXPedssLpvobQ',
    appId: '1:361248548377:web:880172eebabf10dcb16c88',
    messagingSenderId: '361248548377',
    projectId: 'idhamghatfan-2231730135',
    authDomain: 'idhamghatfan-2231730135.firebaseapp.com',
    databaseURL: 'https://idhamghatfan-2231730135-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idhamghatfan-2231730135.appspot.com',
    measurementId: 'G-1W560T2LB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwHVmfGThLznEruRFupsjk3ft9ZJnmjXU',
    appId: '1:361248548377:android:8cf93fb1c9a65dabb16c88',
    messagingSenderId: '361248548377',
    projectId: 'idhamghatfan-2231730135',
    databaseURL: 'https://idhamghatfan-2231730135-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idhamghatfan-2231730135.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCssSsiOc-Rzk5M7_UhwF8h38Ku5g4viMM',
    appId: '1:361248548377:ios:91da8a93e3b47d39b16c88',
    messagingSenderId: '361248548377',
    projectId: 'idhamghatfan-2231730135',
    databaseURL: 'https://idhamghatfan-2231730135-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idhamghatfan-2231730135.appspot.com',
    iosBundleId: 'com.example.muhammadIdham2231730135',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWApQqZcIGQWVm7dOFNcWXPedssLpvobQ',
    appId: '1:361248548377:web:c8fe48fc2c93547fb16c88',
    messagingSenderId: '361248548377',
    projectId: 'idhamghatfan-2231730135',
    authDomain: 'idhamghatfan-2231730135.firebaseapp.com',
    databaseURL: 'https://idhamghatfan-2231730135-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idhamghatfan-2231730135.appspot.com',
    measurementId: 'G-2NHZ2NYJXG',
  );

}